# Alfresco Vagrant Web Box
#
# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX_OS=ENV['BOX_OS'] || "precise64"
JSONFILE=ENV['JSON'] || "alfresco-allinone-dev.json"

print "Using '"+BOX_OS+"' as source Vagrant box\n"
print "Using '"+JSONFILE+"' as JSON Chef configuration\n"

Vagrant.configure("2") do |config|
  provisioner = JSON.parse(IO.read(JSONFILE))["provisioners"][0]
  attributes = provisioner["json"]
  run_list = provisioner["run_list"]

  # Box env configuration
  config.vm.provider :virtualbox do |vb,override|
    if BOX_OS.eql? "centos64"
      override.vm.box_url         = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-i386-v20130731.box"
      override.vm.box             = "centos64"
    elsif BOX_OS.eql? "precise64"
      override.vm.box_url         = "http://files.vagrantup.com/precise64.box"
      override.vm.box             = "precise64"
    end
    vb.customize ["modifyvm", :id, "--memory", 4096]
    vb.customize ["modifyvm", :id, "--cpus", 4]
  end

  config.vm.network :private_network, ip:  attributes["ip"]
  config.vm.hostname = attributes["hostname"]

  config.omnibus.chef_version = "11.16.2"

  config.vm.provision :chef_solo do |chef|
    # Used as Vagrant cache during build
    chef.provisioning_path  = "/tmp/vagrant-chef-solo"
    chef.file_cache_path    = chef.provisioning_path
    chef.cookbooks_path     = "../common/vendor-cookbooks"
    chef.data_bags_path     = "../common/data_bags"

    # Add this layer's Run List
    run_list.each do |recipe|
      chef.add_recipe "recipe[#{recipe}]"
    end

    # Pass the rest of the attributes
    chef.json = attributes
  end
end
