# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.require_version ">= 1.6.0"

Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-7.1"
  config.vm.box_url = "https://atlas.hashicorp.com/bento/boxes/centos-7.1"
  config.vm.synced_folder "../", "/spk/"
  config.vm.network :private_network, ip: "172.17.8.23"

  config.vm.define "image-builder" do
    config.vm.provision "shell", path: "install-packer.sh"
    config.vm.provision "shell", path: "install-vagrant.sh"
    config.vm.provision "shell", path: "install-docker.sh"
    config.vm.provision "shell", path: "pull-docker-images.sh"
    config.vm.provision "shell", path: "check-docker-daemon.sh"
    config.vm.provision "shell", path: "build-docker-images.sh"
  end
end
