# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.require_version ">= 1.6.0"

Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-7.1"
  config.vm.box_url = "https://atlas.hashicorp.com/bento/boxes/centos-7.1"
  config.vm.synced_folder "../", "/spk/", :nfs => true, :mount_options => ['nolock,timeo=6000']

  ip = "172.17.8.#{i+100}"
  config.vm.network :private_network, ip: ip

  # Uncomment below to enable NFS for sharing the host machine into the coreos-vagrant VM.
  #config.vm.synced_folder ".", "/home/core/share", id: "core", :nfs => true, :mount_options => ['nolock,vers=3,udp']
  $shared_folders.each_with_index do |(host_folder, guest_folder), index|
    config.vm.synced_folder host_folder.to_s, guest_folder.to_s, id: "core-share%02d" % index, nfs: true, mount_options: ['nolock,vers=3,udp']
  end

  if $share_home
    config.vm.synced_folder ENV['HOME'], ENV['HOME'], id: "home", :nfs => true, :mount_options => ['nolock,vers=3,udp']
  end

  # plugin conflict
  # if Vagrant.has_plugin?("vagrant-vbguest") then
  #   config.vbguest.auto_update = false
  # end

  config.vm.define "image-builder" do
    config.vm.provision "shell", path: "install-packer.sh"
    config.vm.provision "shell", path: "install-vagrant.sh"
    config.vm.provision "shell", path: "install-docker.sh"
    config.vm.provision "shell", path: "pull-docker-images.sh"
    config.vm.provision "shell", path: "build-docker-images.sh"
  end
end
